///////////////////////////////////////////////////////////////////////////////
// TcAsyncBufferReadingDrvInterfaces.h

#pragma once

#include "TcInterfaces.h"
#include "TcAsyncBufferReadingDrvServices.h"

// defining new interfaces provided by this driver
/* for example
struct __declspec(novtable) ITcAsyncBufferReadingDrvShortName : public ITcUnknown
{
	virtual ULONG TCOMAPI DoSomething(ULONG value1, UINT value2=0)=0;
	TCOMMETHOD(DoSomethingElse(PVOID ptr));
};
_TCOM_SMARTPTR_TYPEDEF(ITcAsyncBufferReadingDrvShortName, IID_ITcAsyncBufferReadingDrvShortName);
*/


///<AutoGeneratedContent id="Interfaces">
///</AutoGeneratedContent>
