///////////////////////////////////////////////////////////////////////////////
// TcAsyncBufferReadingDrvServices.h

#pragma once

#include "TcServices.h"

const ULONG DrvID_TcAsyncBufferReadingDrv = 0x3F000000;
#define SRVNAME_TCASYNCBUFFERREADINGDRV "TcAsyncBufferReadingDrv"


///<AutoGeneratedContent id="ClassIDs">
const CTCID CID_TcAsyncBufferReadingDrvCTcAsyncBufferReadingModule = {0x488f2bd6,0x00cb,0x42c1,{0x96,0xdd,0x46,0xb1,0x1f,0xd0,0xc6,0x3c}};
const CTCID CID_TcAsyncBufferReadingDrvCTcFileWriteDetectModule = {0x0669b74f,0x3129,0x46da,{0x8a,0x36,0xe0,0xaf,0x13,0x89,0xf4,0x1d}};
///</AutoGeneratedContent>

///<AutoGeneratedContent id="ParameterIDs">
const PTCID PID_TcAsyncBufferReadingModuleParameter = 0x00000001;
///</AutoGeneratedContent>

///<AutoGeneratedContent id="InterfaceIDs">
///</AutoGeneratedContent>

///<AutoGeneratedContent id="DataTypes">
typedef struct _TcAsyncBufferReadingModuleParameter
{
	ULONG nSegmentSize;
	ULONG nTimeout;
	ULONG nReadBufferSize;
} TcAsyncBufferReadingModuleParameter, *PTcAsyncBufferReadingModuleParameter;

typedef struct _TcAsyncBufferReadingModuleInputs
{
	bool bExecute;
	unsigned char reserved1[3];
	ULONG nOffset;
} TcAsyncBufferReadingModuleInputs, *PTcAsyncBufferReadingModuleInputs;

typedef struct _TcAsyncBufferReadingModuleOutputs
{
	bool bBusy;
	bool bError;
	unsigned char reserved1[2];
	ULONG iErrorId;
	ULONG nBytesRead;
} TcAsyncBufferReadingModuleOutputs, *PTcAsyncBufferReadingModuleOutputs;

typedef struct _TcAsyncBufferReadingModuleData
{
	float Values[32];
} TcAsyncBufferReadingModuleData, *PTcAsyncBufferReadingModuleData;

typedef struct _TcFileWriteDetectModuleInputs
{
	bool bBusy;
	bool bError;
	unsigned char reserved1[2];
	ULONG nBytesWritten;
} TcFileWriteDetectModuleInputs, *PTcFileWriteDetectModuleInputs;

typedef struct _TcFileWriteDetectModuleOutputs
{
	bool bExecuteOut;
	unsigned char reserved1[3];
	ULONG nOffset;
} TcFileWriteDetectModuleOutputs, *PTcFileWriteDetectModuleOutputs;

///</AutoGeneratedContent>
