///////////////////////////////////////////////////////////////////////////////
// TcAsyncBufferReadingDrvClassFactory.cpp
#include "TcPch.h"
#pragma hdrstop

#include "TcAsyncBufferReadingDrvClassFactory.h"
#include "TcAsyncBufferReadingDrvServices.h"
#include "TcAsyncBufferReadingModule.h"
#include "TcFileWriteDetectModule.h"

BEGIN_CLASS_MAP(CTcAsyncBufferReadingDrvClassFactory)
///<AutoGeneratedContent id="ClassMap">
	CLASS_ENTRY(CID_TcAsyncBufferReadingDrvCTcAsyncBufferReadingModule, SRVNAME_TCASYNCBUFFERREADINGDRV "!CTcAsyncBufferReadingModule", CTcAsyncBufferReadingModule)
	CLASS_ENTRY(CID_TcAsyncBufferReadingDrvCTcFileWriteDetectModule, SRVNAME_TCASYNCBUFFERREADINGDRV "!CTcFileWriteDetectModule", CTcFileWriteDetectModule)
///</AutoGeneratedContent>
END_CLASS_MAP()

CTcAsyncBufferReadingDrvClassFactory::CTcAsyncBufferReadingDrvClassFactory() : CObjClassFactory()
{
	TcDbgUnitSetImageName(TCDBG_UNIT_IMAGE_NAME(SRVNAME_TCASYNCBUFFERREADINGDRV)); 
}

