///////////////////////////////////////////////////////////////////////////////
// TcFileWriteDetectModule.h
#pragma once

#include "TcIoInterfaces.h"
#include "TcRtInterfaces.h"
#include "TcAsyncBufferReadingDrvInterfaces.h"

class CTcFileWriteDetectModule 
	: public ITComObject
	, public ITcADI
///<AutoGeneratedContent id="InheritanceList">
	, public ITcCyclic
///</AutoGeneratedContent>
{
public:
	DECLARE_IUNKNOWN()
	DECLARE_IPERSIST(CID_TcAsyncBufferReadingDrvCTcFileWriteDetectModule)
	DECLARE_ITCOMOBJECT_LOCKOP()
	DECLARE_OBJDATAAREA_MAP()
	DECLARE_ITCADI()

	CTcFileWriteDetectModule();

	virtual	~CTcFileWriteDetectModule();


///<AutoGeneratedContent id="InterfaceMembers">
	// ITcCyclic
	virtual HRESULT TCOMAPI CycleUpdate(ITcTask* ipTask, ITcUnknown* ipCaller, ULONG_PTR context);

///</AutoGeneratedContent>

protected:
	DECLARE_ITCOMOBJECT_SETSTATE();

	HRESULT AddModuleToCaller();
	VOID RemoveModuleFromCaller();

		
	// Tracing
	CTcTrace m_Trace;

///<AutoGeneratedContent id="Members">
	TcTraceLevel m_TraceLevelMax;
	TcFileWriteDetectModuleInputs m_Inputs;
	TcFileWriteDetectModuleOutputs m_Outputs;
	ITcCyclicCallerInfoPtr m_spCyclicCaller;
///</AutoGeneratedContent>

	// TODO: Custom variable
	UINT m_counter;
	BYTE m_bBusy;
	ULONG m_nOffset;
};
