///////////////////////////////////////////////////////////////////////////////
// TcAsyncBufferWritingDrvInterfaces.h

#pragma once

#include "TcInterfaces.h"
#include "TcAsyncBufferWritingDrvServices.h"

///<AutoGeneratedContent id="Interfaces">
///</AutoGeneratedContent>
