///////////////////////////////////////////////////////////////////////////////
// TcAsyncFileFindDrvClassFactory.cpp
#include "TcPch.h"
#pragma hdrstop

#include "TcAsyncFileFindDrvClassFactory.h"
#include "TcAsyncFileFindDrvServices.h"
#include "TcAsyncFileFindDrvVersion.h"
#include "TcAsyncFileFindModule.h"

BEGIN_CLASS_MAP(CTcAsyncFileFindDrvClassFactory)
///<AutoGeneratedContent id="ClassMap">
	CLASS_ENTRY(CID_TcAsyncFileFindDrvCTcAsyncFileFindModule, SRVNAME_TCASYNCFILEFINDDRV "!CTcAsyncFileFindModule", CTcAsyncFileFindModule)
///</AutoGeneratedContent>
END_CLASS_MAP()

CTcAsyncFileFindDrvClassFactory::CTcAsyncFileFindDrvClassFactory() : CObjClassFactory()
{
	TcDbgUnitSetImageName(TCDBG_UNIT_IMAGE_NAME(SRVNAME_TCASYNCFILEFINDDRV)); 
#if defined(TCDBG_UNIT_VERSION)
	TcDbgUnitSetVersion(TCDBG_UNIT_VERSION(TcAsyncFileFindDrv));
#endif //defined(TCDBG_UNIT_VERSION)
}

