///////////////////////////////////////////////////////////////////////////////
// TcAsyncFileFindModule.h
#pragma once

#include "TcAsyncFileFindDrvInterfaces.h"
#include "TcFileAccessInterfaces.h"
#include "TcFsmFileFind.h"

class CTcAsyncFileFindModule 
	: public ITComObject
	, public ITcADI
	, public ITcWatchSource
///<AutoGeneratedContent id="InheritanceList">
	, public ITcCyclic
///</AutoGeneratedContent>
{
public:
	DECLARE_IUNKNOWN()
	DECLARE_IPERSIST(CID_TcAsyncFileFindDrvCTcAsyncFileFindModule)
	DECLARE_ITCOMOBJECT_LOCKOP()
	DECLARE_ITCADI()
	DECLARE_ITCWATCHSOURCE()
	DECLARE_OBJPARAWATCH_MAP()
	DECLARE_OBJDATAAREA_MAP()

	CTcAsyncFileFindModule();
	virtual	~CTcAsyncFileFindModule();


///<AutoGeneratedContent id="InterfaceMembers">
	// ITcCyclic
	virtual HRESULT TCOMAPI CycleUpdate(ITcTask* ipTask, ITcUnknown* ipCaller, ULONG_PTR context);

///</AutoGeneratedContent>

protected:
	DECLARE_ITCOMOBJECT_SETSTATE();

	HRESULT AddModuleToCaller();
	VOID RemoveModuleFromCaller();

	// Tracing
	CTcTrace m_Trace;

///<AutoGeneratedContent id="Members">
	TcTraceLevel m_TraceLevelMax;
	TcAsyncFileFindModuleParameter m_Parameter;
	STRING259 m_FilePath;
	TcAsyncFileFindModuleInputs m_Inputs;
	TcAsyncFileFindModuleOutputs m_Outputs;
	ITcCyclicCallerInfoPtr m_spCyclicCaller;
///</AutoGeneratedContent>

	// Custom variable
	ITcFileAccessAsyncPtr m_spFileAccessAsync;
	CTcFsmFileFind m_fsmFileFind;
	UINT m_counter;
};
